//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FR.Repository
{
    using System;
    using System.Collections.Generic;
    
    public partial class fr_BizFoodTypes
    {
        public int BizFoodTypeId { get; set; }
        public int BizInfoId { get; set; }
        public int FoodTypeId { get; set; }
        public System.DateTime AddedDate { get; set; }
        public string AddedBy { get; set; }
        public System.DateTime UpdatedDate { get; set; }
        public string UpdatedBy { get; set; }
        public bool Active { get; set; }
    
        public virtual fr_BizInfos fr_BizInfos { get; set; }
        public virtual fr_FoodTypes fr_FoodTypes { get; set; }
    }
}
