//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FR.Repository
{
    using System;
    using System.Collections.Generic;
    
    public partial class fr_BizRVInfos
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public fr_BizRVInfos()
        {
            this.fr_Reservations = new HashSet<fr_Reservations>();
        }
    
        public int BizRVInfoId { get; set; }
        public int BizInfoId { get; set; }
        public string BizPrice { get; set; }
        public int StandingCapacity { get; set; }
        public int SeatedCapacity { get; set; }
        public string StartTime { get; set; }
        public string EndTime { get; set; }
        public string DiningStyle { get; set; }
        public string PaymentOptions { get; set; }
        public bool AcceptWalkIn { get; set; }
        public string ExecutiveChef { get; set; }
        public string PrivatePartyFacilities { get; set; }
        public string SpecialEvents { get; set; }
        public string Parking { get; set; }
        public string AdditionalDetails { get; set; }
        public System.DateTime AddedDate { get; set; }
        public string AddedBy { get; set; }
        public System.DateTime UpdatedDate { get; set; }
        public string UpdatedBy { get; set; }
        public bool Active { get; set; }
    
        public virtual fr_BizInfos fr_BizInfos { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<fr_Reservations> fr_Reservations { get; set; }
    }
}
