//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FR.Repository
{
    using System;
    using System.Collections.Generic;
    
    public partial class fr_BizHours
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public fr_BizHours()
        {
            this.fr_BizInfos = new HashSet<fr_BizInfos>();
        }
    
        public int BizHourId { get; set; }
        public string LMonStart { get; set; }
        public string LMonClose { get; set; }
        public string LTueStart { get; set; }
        public string LTueClose { get; set; }
        public string LWedStart { get; set; }
        public string LWedClose { get; set; }
        public string LThuStart { get; set; }
        public string LThuClose { get; set; }
        public string LFriStart { get; set; }
        public string LFriClose { get; set; }
        public string LSatStart { get; set; }
        public string LSatClose { get; set; }
        public string LSunStart { get; set; }
        public string LSunClose { get; set; }
        public string MonStart { get; set; }
        public string MonClose { get; set; }
        public string TueStart { get; set; }
        public string TueClose { get; set; }
        public string WedStart { get; set; }
        public string WedClose { get; set; }
        public string ThuStart { get; set; }
        public string ThuClose { get; set; }
        public string FriStart { get; set; }
        public string FriClose { get; set; }
        public string SatStart { get; set; }
        public string SatClose { get; set; }
        public string SunStart { get; set; }
        public string SunColse { get; set; }
        public int ZoneNameId { get; set; }
        public System.DateTime AddedDate { get; set; }
        public string AddedBy { get; set; }
        public System.DateTime UpdatedDate { get; set; }
        public string UpdatedBy { get; set; }
        public bool Active { get; set; }
    
        public virtual fr_ZoneNames fr_ZoneNames { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<fr_BizInfos> fr_BizInfos { get; set; }
    }
}
