//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FR.Repository
{
    using System;
    using System.Collections.Generic;
    
    public partial class fr_BizImages
    {
        public int BizImageId { get; set; }
        public int BizInfoId { get; set; }
        public string SmallImageName { get; set; }
        public string BigImageName { get; set; }
        public bool Active { get; set; }
    
        public virtual fr_BizInfos fr_BizInfos { get; set; }
    }
}
