//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FR.Repository
{
    using System;
    using System.Collections.Generic;
    
    public partial class fr_Products
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public fr_Products()
        {
            this.fr_AddSides = new HashSet<fr_AddSides>();
            this.fr_CheeseAmounts = new HashSet<fr_CheeseAmounts>();
            this.fr_CrustChoices = new HashSet<fr_CrustChoices>();
            this.fr_FamilyMeals = new HashSet<fr_FamilyMeals>();
            this.fr_OrderItems = new HashSet<fr_OrderItems>();
            this.fr_ProductDressings = new HashSet<fr_ProductDressings>();
            this.fr_ProductSizes = new HashSet<fr_ProductSizes>();
            this.fr_ProductToppings = new HashSet<fr_ProductToppings>();
            this.fr_SauceChoices = new HashSet<fr_SauceChoices>();
            this.fr_SideChoices = new HashSet<fr_SideChoices>();
        }
    
        public int ProductId { get; set; }
        public int CategoryId { get; set; }
        public int CookMethodId { get; set; }
        public int FoodTypeId { get; set; }
        public int MealSectionId { get; set; }
        public string Title { get; set; }
        public string Description { get; set; }
        public decimal UnitPrice { get; set; }
        public decimal BizPrice { get; set; }
        public int DiscountPercentage { get; set; }
        public string SmallImage { get; set; }
        public string BigImage { get; set; }
        public int MaxNumOfFreeTopping { get; set; }
        public bool IsSpicy { get; set; }
        public bool IsVegetarian { get; set; }
        public bool IsMostPopular { get; set; }
        public bool IsFamilyDinner { get; set; }
        public System.DateTime AddedDate { get; set; }
        public string AddedBy { get; set; }
        public System.DateTime UpdatedDate { get; set; }
        public string UpdatedBy { get; set; }
        public bool Active { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<fr_AddSides> fr_AddSides { get; set; }
        public virtual fr_Categories fr_Categories { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<fr_CheeseAmounts> fr_CheeseAmounts { get; set; }
        public virtual fr_CookMethods fr_CookMethods { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<fr_CrustChoices> fr_CrustChoices { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<fr_FamilyMeals> fr_FamilyMeals { get; set; }
        public virtual fr_FoodTypes fr_FoodTypes { get; set; }
        public virtual fr_MealSections fr_MealSections { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<fr_OrderItems> fr_OrderItems { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<fr_ProductDressings> fr_ProductDressings { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<fr_ProductSizes> fr_ProductSizes { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<fr_ProductToppings> fr_ProductToppings { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<fr_SauceChoices> fr_SauceChoices { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<fr_SideChoices> fr_SideChoices { get; set; }
    }
}
