//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FR.Repository
{
    using System;
    using System.Collections.Generic;
    
    public partial class fr_Reservations
    {
        public int ReservationId { get; set; }
        public int BizRVInfoId { get; set; }
        public string FirstName { get; set; }
        public string LastName { get; set; }
        public string Phone { get; set; }
        public string Email { get; set; }
        public string RVDate { get; set; }
        public string RVTime { get; set; }
        public int PartySize { get; set; }
        public string Message { get; set; }
        public System.DateTime AddedDate { get; set; }
        public string AddedBy { get; set; }
        public System.DateTime UpdatedDate { get; set; }
        public string UpdatedBy { get; set; }
        public bool Active { get; set; }
    
        public virtual fr_BizRVInfos fr_BizRVInfos { get; set; }
    }
}
