//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FR.Repository
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class foodreadyEntities : DbContext
    {
        public foodreadyEntities()
            : base("name=foodreadyEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<C__MigrationHistory> C__MigrationHistory { get; set; }
        public virtual DbSet<AspNetRole> AspNetRoles { get; set; }
        public virtual DbSet<AspNetUserClaim> AspNetUserClaims { get; set; }
        public virtual DbSet<AspNetUserLogin> AspNetUserLogins { get; set; }
        public virtual DbSet<AspNetUser> AspNetUsers { get; set; }
        public virtual DbSet<fr_Address> fr_Address { get; set; }
        public virtual DbSet<fr_AddSides> fr_AddSides { get; set; }
        public virtual DbSet<fr_BizCuisines> fr_BizCuisines { get; set; }
        public virtual DbSet<fr_BizFoodTypes> fr_BizFoodTypes { get; set; }
        public virtual DbSet<fr_BizHours> fr_BizHours { get; set; }
        public virtual DbSet<fr_BizImages> fr_BizImages { get; set; }
        public virtual DbSet<fr_BizInfos> fr_BizInfos { get; set; }
        public virtual DbSet<fr_BizRVInfos> fr_BizRVInfos { get; set; }
        public virtual DbSet<fr_Categories> fr_Categories { get; set; }
        public virtual DbSet<fr_CheeseAmounts> fr_CheeseAmounts { get; set; }
        public virtual DbSet<fr_ContactInfos> fr_ContactInfos { get; set; }
        public virtual DbSet<fr_ConvertedPoints> fr_ConvertedPoints { get; set; }
        public virtual DbSet<fr_CookMethods> fr_CookMethods { get; set; }
        public virtual DbSet<fr_CreditCards> fr_CreditCards { get; set; }
        public virtual DbSet<fr_CreditCardTypes> fr_CreditCardTypes { get; set; }
        public virtual DbSet<fr_CrustChoices> fr_CrustChoices { get; set; }
        public virtual DbSet<fr_CuisineTypes> fr_CuisineTypes { get; set; }
        public virtual DbSet<fr_DayOfCloses> fr_DayOfCloses { get; set; }
        public virtual DbSet<fr_DiscountCoupons> fr_DiscountCoupons { get; set; }
        public virtual DbSet<fr_Dressings> fr_Dressings { get; set; }
        public virtual DbSet<fr_Drivers> fr_Drivers { get; set; }
        public virtual DbSet<fr_FamilyMeals> fr_FamilyMeals { get; set; }
        public virtual DbSet<fr_FavorRestaurants> fr_FavorRestaurants { get; set; }
        public virtual DbSet<fr_FoodTypes> fr_FoodTypes { get; set; }
        public virtual DbSet<fr_FreeItemCoupons> fr_FreeItemCoupons { get; set; }
        public virtual DbSet<fr_GiftCards> fr_GiftCards { get; set; }
        public virtual DbSet<fr_Hotel> fr_Hotel { get; set; }
        public virtual DbSet<fr_HotelTypes> fr_HotelTypes { get; set; }
        public virtual DbSet<fr_MealSections> fr_MealSections { get; set; }
        public virtual DbSet<fr_OrderItems> fr_OrderItems { get; set; }
        public virtual DbSet<fr_Orders> fr_Orders { get; set; }
        public virtual DbSet<fr_OrderStatuses> fr_OrderStatuses { get; set; }
        public virtual DbSet<fr_ProductDressings> fr_ProductDressings { get; set; }
        public virtual DbSet<fr_Products> fr_Products { get; set; }
        public virtual DbSet<fr_ProductSizes> fr_ProductSizes { get; set; }
        public virtual DbSet<fr_ProductToppings> fr_ProductToppings { get; set; }
        public virtual DbSet<fr_Reservations> fr_Reservations { get; set; }
        public virtual DbSet<fr_RewardVouchers> fr_RewardVouchers { get; set; }
        public virtual DbSet<fr_SauceChoices> fr_SauceChoices { get; set; }
        public virtual DbSet<fr_SideChoices> fr_SideChoices { get; set; }
        public virtual DbSet<fr_Toppings> fr_Toppings { get; set; }
        public virtual DbSet<fr_UserDetails> fr_UserDetails { get; set; }
        public virtual DbSet<fr_Votes> fr_Votes { get; set; }
        public virtual DbSet<fr_ZoneNames> fr_ZoneNames { get; set; }
    }
}
