//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FR.Domain.Model.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class BizInfo
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public BizInfo()
        {
            this.BizCuisines = new HashSet<BizCuisine>();
            this.BizFoodTypes = new HashSet<BizFoodType>();
            this.BizImages = new HashSet<BizImage>();
            this.BizRVInfos = new HashSet<BizRVInfo>();
            this.DayOfCloses = new HashSet<DayOfClose>();
            this.DiscountCoupons = new HashSet<DiscountCoupon>();
            this.FavorRestaurants = new HashSet<FavorRestaurant>();
            this.FreeItemCoupons = new HashSet<FreeItemCoupon>();
            this.Orders = new HashSet<Order>();
            this.Votes = new HashSet<Vote>();
        }
    
        public int BizInfoId { get; set; }
        public string UserId { get; set; }
        public string BizTitle { get; set; }
        public string Description { get; set; }
        public string ImageUrl { get; set; }
        public int AddressId { get; set; }
        public string YelpBizId { get; set; }
        public string Latitude { get; set; }
        public string Longitude { get; set; }
        public int ContactInfoId { get; set; }
        public int BizHourId { get; set; }
        public string Fax { get; set; }
        public string FoodCost { get; set; }
        public bool HasDiscountCoupons { get; set; }
        public bool HasFreeItemCoupons { get; set; }
        public bool HasBreakfast { get; set; }
        public bool HasLunchSpecial { get; set; }
        public bool CanOrderForNextday { get; set; }
        public string Website { get; set; }
        public bool Delivery { get; set; }
        public int DeliveryRadius { get; set; }
        public decimal DeliveryFee { get; set; }
        public decimal DeliveryMinimum { get; set; }
        public decimal TaxPercentageRate { get; set; }
        public int RatingVotes { get; set; }
        public int TotalRating { get; set; }
        public int FiveStarVotes { get; set; }
        public int FourStarVotes { get; set; }
        public int ThreeStarVotes { get; set; }
        public int TwoStarVotes { get; set; }
        public int OneStarVotes { get; set; }
        public System.DateTime AddedDate { get; set; }
        public string AddedBy { get; set; }
        public System.DateTime UpdatedDate { get; set; }
        public string UpdatedBy { get; set; }
        public bool Active { get; set; }
    
        public virtual AspNetUser AspNetUser { get; set; }
        public virtual Address Address { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<BizCuisine> BizCuisines { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<BizFoodType> BizFoodTypes { get; set; }
        public virtual BizHour BizHour { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<BizImage> BizImages { get; set; }
        public virtual ContactInfo ContactInfo { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<BizRVInfo> BizRVInfos { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DayOfClose> DayOfCloses { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DiscountCoupon> DiscountCoupons { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<FavorRestaurant> FavorRestaurants { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<FreeItemCoupon> FreeItemCoupons { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Order> Orders { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Vote> Votes { get; set; }
    }
}
