//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FR.Domain.Model.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class DayOfClose
    {
        public int DayOfCloseId { get; set; }
        public int BizInfoId { get; set; }
        public string Title { get; set; }
        public System.DateTime CloseDay { get; set; }
        public int ZoneNameId { get; set; }
        public System.DateTime AddedDate { get; set; }
        public string AddedBy { get; set; }
        public System.DateTime UpdatedDate { get; set; }
        public string UpdatedBy { get; set; }
        public bool Active { get; set; }
    
        public virtual BizInfo BizInfo { get; set; }
        public virtual ZoneName ZoneName { get; set; }
    }
}
