//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FR.Domain.Model.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class fr_BizInfos
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public fr_BizInfos()
        {
            this.fr_BizCuisines = new HashSet<fr_BizCuisines>();
            this.fr_BizFoodTypes = new HashSet<fr_BizFoodTypes>();
            this.fr_BizImages = new HashSet<fr_BizImages>();
            this.fr_BizRVInfos = new HashSet<fr_BizRVInfos>();
            this.fr_DayOfCloses = new HashSet<fr_DayOfCloses>();
            this.fr_DiscountCoupons = new HashSet<fr_DiscountCoupons>();
            this.fr_FavorRestaurants = new HashSet<fr_FavorRestaurants>();
            this.fr_FreeItemCoupons = new HashSet<fr_FreeItemCoupons>();
            this.fr_Orders = new HashSet<fr_Orders>();
            this.fr_Votes = new HashSet<fr_Votes>();
        }
    
        public int BizInfoId { get; set; }
        public string UserId { get; set; }
        public string BizTitle { get; set; }
        public string Description { get; set; }
        public string ImageUrl { get; set; }
        public int AddressId { get; set; }
        public string YelpBizId { get; set; }
        public string Latitude { get; set; }
        public string Longitude { get; set; }
        public int ContactInfoId { get; set; }
        public int BizHourId { get; set; }
        public string Fax { get; set; }
        public string FoodCost { get; set; }
        public bool HasDiscountCoupons { get; set; }
        public bool HasFreeItemCoupons { get; set; }
        public bool HasBreakfast { get; set; }
        public bool HasLunchSpecial { get; set; }
        public bool CanOrderForNextday { get; set; }
        public string Website { get; set; }
        public bool Delivery { get; set; }
        public int DeliveryRadius { get; set; }
        public decimal DeliveryFee { get; set; }
        public decimal DeliveryMinimum { get; set; }
        public decimal TaxPercentageRate { get; set; }
        public int RatingVotes { get; set; }
        public int TotalRating { get; set; }
        public int FiveStarVotes { get; set; }
        public int FourStarVotes { get; set; }
        public int ThreeStarVotes { get; set; }
        public int TwoStarVotes { get; set; }
        public int OneStarVotes { get; set; }
        public System.DateTime AddedDate { get; set; }
        public string AddedBy { get; set; }
        public System.DateTime UpdatedDate { get; set; }
        public string UpdatedBy { get; set; }
        public bool Active { get; set; }
    
        public virtual AspNetUser AspNetUser { get; set; }
        public virtual fr_Address fr_Address { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<fr_BizCuisines> fr_BizCuisines { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<fr_BizFoodTypes> fr_BizFoodTypes { get; set; }
        public virtual fr_BizHours fr_BizHours { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<fr_BizImages> fr_BizImages { get; set; }
        public virtual fr_ContactInfos fr_ContactInfos { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<fr_BizRVInfos> fr_BizRVInfos { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<fr_DayOfCloses> fr_DayOfCloses { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<fr_DiscountCoupons> fr_DiscountCoupons { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<fr_FavorRestaurants> fr_FavorRestaurants { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<fr_FreeItemCoupons> fr_FreeItemCoupons { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<fr_Orders> fr_Orders { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<fr_Votes> fr_Votes { get; set; }
    }
}
