//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FR.Domain.Model.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class fr_ProductToppings
    {
        public int ProductToppingId { get; set; }
        public int ProductId { get; set; }
        public int ToppingId { get; set; }
        public string ToppingTitle { get; set; }
        public decimal ExtraToppingPrice { get; set; }
        public decimal Increment { get; set; }
        public System.DateTime AddedDate { get; set; }
        public string AddedBy { get; set; }
        public System.DateTime UpdatedDate { get; set; }
        public string UpdatedBy { get; set; }
        public bool Active { get; set; }
    
        public virtual fr_Products fr_Products { get; set; }
        public virtual fr_Toppings fr_Toppings { get; set; }
    }
}
