//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FR.Domain.Model.Entities
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class FRShoppingEntities : DbContext
    {
        public FRShoppingEntities()
            : base("name=FRShoppingEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<C__MigrationHistory> C__MigrationHistory { get; set; }
        public virtual DbSet<AspNetRole> AspNetRoles { get; set; }
        public virtual DbSet<AspNetUserClaim> AspNetUserClaims { get; set; }
        public virtual DbSet<AspNetUserLogin> AspNetUserLogins { get; set; }
        public virtual DbSet<AspNetUser> AspNetUsers { get; set; }
        public virtual DbSet<Address> Addresses { get; set; }
        public virtual DbSet<AddSide> AddSides { get; set; }
        public virtual DbSet<BizCuisine> BizCuisines { get; set; }
        public virtual DbSet<BizFoodType> BizFoodTypes { get; set; }
        public virtual DbSet<BizHour> BizHours { get; set; }
        public virtual DbSet<BizImage> BizImages { get; set; }
        public virtual DbSet<BizInfo> BizInfos { get; set; }
        public virtual DbSet<BizRVInfo> BizRVInfos { get; set; }
        public virtual DbSet<Category> Categories { get; set; }
        public virtual DbSet<CheeseAmount> CheeseAmounts { get; set; }
        public virtual DbSet<ContactInfo> ContactInfos { get; set; }
        public virtual DbSet<ConvertedPoint> ConvertedPoints { get; set; }
        public virtual DbSet<CookMethod> CookMethods { get; set; }
        public virtual DbSet<CreditCard> CreditCards { get; set; }
        public virtual DbSet<CreditCardType> CreditCardTypes { get; set; }
        public virtual DbSet<CrustChoice> CrustChoices { get; set; }
        public virtual DbSet<CuisineType> CuisineTypes { get; set; }
        public virtual DbSet<DayOfClose> DayOfCloses { get; set; }
        public virtual DbSet<DiscountCoupon> DiscountCoupons { get; set; }
        public virtual DbSet<Dressing> Dressings { get; set; }
        public virtual DbSet<Driver> Drivers { get; set; }
        public virtual DbSet<FamilyMeal> FamilyMeals { get; set; }
        public virtual DbSet<FavorRestaurant> FavorRestaurants { get; set; }
        public virtual DbSet<FoodType> FoodTypes { get; set; }
        public virtual DbSet<FreeItemCoupon> FreeItemCoupons { get; set; }
        public virtual DbSet<GiftCard> GiftCards { get; set; }
        public virtual DbSet<Hotel> Hotels { get; set; }
        public virtual DbSet<HotelType> HotelTypes { get; set; }
        public virtual DbSet<MealSection> MealSections { get; set; }
        public virtual DbSet<OrderItem> OrderItems { get; set; }
        public virtual DbSet<Order> Orders { get; set; }
        public virtual DbSet<OrderStatus> OrderStatuses { get; set; }
        public virtual DbSet<ProductDressing> ProductDressings { get; set; }
        public virtual DbSet<Product> Products { get; set; }
        public virtual DbSet<ProductSize> ProductSizes { get; set; }
        public virtual DbSet<ProductTopping> ProductToppings { get; set; }
        public virtual DbSet<Reservation> Reservations { get; set; }
        public virtual DbSet<RewardVoucher> RewardVouchers { get; set; }
        public virtual DbSet<SauceChoice> SauceChoices { get; set; }
        public virtual DbSet<SideChoice> SideChoices { get; set; }
        public virtual DbSet<Topping> Toppings { get; set; }
        public virtual DbSet<UserDetail> UserDetails { get; set; }
        public virtual DbSet<Vote> Votes { get; set; }
        public virtual DbSet<ZoneName> ZoneNames { get; set; }
    }
}
