//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FR.Domain.Model.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class GiftCard
    {
        public int GiftCardId { get; set; }
        public string GiftCardCode { get; set; }
        public string UserId { get; set; }
        public int CreditCardId { get; set; }
        public int LastPayBizInfoId { get; set; }
        public string UserEmail { get; set; }
        public string RecipientEmail { get; set; }
        public decimal Amount { get; set; }
        public System.DateTime LastTimeUse { get; set; }
        public decimal Balance { get; set; }
        public decimal LastPayAmount { get; set; }
        public decimal LastOrderTotal { get; set; }
        public System.DateTime AddedDate { get; set; }
        public string AddedBy { get; set; }
        public System.DateTime UpdatedDate { get; set; }
        public string UpdatedBy { get; set; }
        public bool Active { get; set; }
    
        public virtual AspNetUser AspNetUser { get; set; }
        public virtual CreditCard CreditCard { get; set; }
    }
}
