//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FR.Domain.Model.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class Order
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Order()
        {
            this.OrderItems = new HashSet<OrderItem>();
        }
    
        public int OrderId { get; set; }
        public string LogonName { get; set; }
        public int BizInfoId { get; set; }
        public int OrderStatusId { get; set; }
        public int CreditCardId { get; set; }
        public bool IsLoggedUser { get; set; }
        public bool IsPayPalPayment { get; set; }
        public bool IsGiftCardPayment { get; set; }
        public int GiftCardId { get; set; }
        public decimal GiftCardAmountPay { get; set; }
        public string CustomerMessage { get; set; }
        public string ScheduleDate { get; set; }
        public string ScheduleTime { get; set; }
        public string CouponChoice { get; set; }
        public bool IsDelivery { get; set; }
        public decimal DeliveryCharge { get; set; }
        public decimal BizDiscountAmount { get; set; }
        public decimal DiscountAmount { get; set; }
        public decimal SubTotal { get; set; }
        public decimal BizSubTotal { get; set; }
        public decimal OrderTax { get; set; }
        public decimal OrderTotal { get; set; }
        public decimal BizOrderTotal { get; set; }
        public decimal ServiceCharge { get; set; }
        public string DriverName { get; set; }
        public decimal DriverTip { get; set; }
        public string FirstName { get; set; }
        public string LastName { get; set; }
        public string Street { get; set; }
        public string City { get; set; }
        public string State { get; set; }
        public string ZipCode { get; set; }
        public string Phone { get; set; }
        public string Email { get; set; }
        public string IpAddress { get; set; }
        public string TransactionId { get; set; }
        public System.DateTime AddedDate { get; set; }
        public string AddedBy { get; set; }
        public System.DateTime UpdatedDate { get; set; }
        public string UpdatedBy { get; set; }
        public bool Active { get; set; }
    
        public virtual BizInfo BizInfo { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<OrderItem> OrderItems { get; set; }
        public virtual OrderStatus OrderStatus { get; set; }
    }
}
